services:
  app:
    build:
      context: ../.
      dockerfile: docker/Dockerfile
    container_name: app
    depends_on:
      - employee-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - SPRING_DATASOURCE_URL=jdbc:postgresql://employee-postgres:5432/employee_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
    networks:
      - default

  employee-postgres:
    image: postgres:16.2
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: employee_db
    ports:
        - "5432:5432"
    healthcheck:
        test: [ "CMD", "pg_isready" ]
        interval: 10s
        timeout: 5s
        retries: 10
    volumes:
        - ./logs:/logs
    networks:
        - default